// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Remote_Development_and_Compilation.MPFProj10.Dev10.Samples.CSharp.CustomProject.Src
{
    internal sealed partial class Vsix
    {
        public const string Id = "AC4F6611-3817-478E-A1A4-ADF38CDBF1DB";
        public const string Name = "CustomProj - AC4F6611-3817-478E-A1A4-ADF38CDBF1DB";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Microsoft IT";
        public const string Tags = "";
    }
}
