// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Remote_Development_and_Compilation.MPFProj10.Dev10.Samples.CSharp.NestedProject.Src
{
    internal sealed partial class Vsix
    {
        public const string Id = "da0eb39c-13bc-41b4-8c29-889d52713634";
        public const string Name = "NestedProj - da0eb39c-13bc-41b4-8c29-889d52713634";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Microsoft IT";
        public const string Tags = "";
    }
}
